FROM klakegg/hugo:0.68.3-ext

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# Installs Pipenv and extra dependencies
RUN apt update && apt install pipenv curl zlib1g-dev libssl-dev -y

# Installs Pyenv
ENV PATH="/root/.pyenv/bin:${PATH}"
RUN curl https://pyenv.run | bash
RUN echo 'eval "$(pyenv init -)"' >> ~/.bashrc

# Adds only python and dependencies files into the image so we don't need to rebuild on content changes
ADD [".python-version", "Pipfile*", "run.sh", "/app/"]

# Installs Python and dependencies
RUN pyenv install && pipenv install --dev

VOLUME ["/app"]

ENTRYPOINT [ "/bin/bash" ]
CMD [ "run.sh" ]