FROM docker.io/library/python:3.9-alpine

ENV HOME /tmp
ENV PIP_NO_CACHE_DIR=off

RUN pip install pipenv

COPY Pipfile Pipfile.lock ./

RUN pipenv install --system --deploy --ignore-pipfile

ADD linkcheckerrc .

ENTRYPOINT [ "linkchecker" ]
